// ============================================================
// HEXA DASHBOARD — CONFIG v3
// ============================================================

const CONFIG = {
  SHEET_HOSPITAL_NETWORK: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRrd9wkjq0MLRYCp5k2fBRnHdjOpeTgGuL6eLwIlQuAAdK0PsANa9zGiiF9Owh-BsC_sRPkdl1S0PC8/pub?gid=0&single=true&output=csv',
  SHEET_ASP_DATA:         'https://docs.google.com/spreadsheets/d/e/2PACX-1vRrd9wkjq0MLRYCp5k2fBRnHdjOpeTgGuL6eLwIlQuAAdK0PsANa9zGiiF9Owh-BsC_sRPkdl1S0PC8/pub?gid=1167367380&single=true&output=csv',
  REFRESH_INTERVAL:  60000,
  TIER_GOLD:   65,
  TIER_SILVER: 50,
  TIER_BRONZE: 35,
  TIER_MIN_CASES: 20,
  UNDERUTILIZED_MAX_CASES: 15,
  UNDERUTILIZED_MIN_ASP_SCORE: 55,
  SCORE_WEIGHT_ASP:      0.60,
  SCORE_WEIGHT_COVERAGE: 0.20,
  SCORE_WEIGHT_VOLUME:   0.20,
  TPA_COL_START: 9,
  TPA_COL_END:   26,
  INSURER_COL_START: 27,
  INSURER_COL_END:   55,
  ACTIVE_CATEGORIES: [
    'Aesthetics / Plastic Surgery','ENT','Laparoscopy','Urology',
    'Proctology','Orthopaedics','Vascular','Kidney Stone','Gynaecology','General Surgery'
  ],
  DELHI_NCR_CITIES: ['delhi','new delhi','noida','gurugram','gurgaon','faridabad','greater noida','ghaziabad'],
  CITY_DISPLAY: {
    'delhi ncr':'Delhi NCR','bangalore':'Bangalore','mumbai':'Mumbai',
    'pune':'Pune','hyderabad':'Hyderabad','ahmedabad':'Ahmedabad','others':'Others'
  },
  // Region → city mapping for inter-city display
  CITY_REGION: {
    'delhi ncr':'North','bangalore':'South','hyderabad':'South',
    'mumbai':'West','pune':'West','ahmedabad':'West','others':'Central'
  },
  ZONE_COLORS: { North:'#3b82f6', South:'#10b981', West:'#f97316', East:'#8b5cf6', Central:'#f59e0b' },
};

// ── Pincode → intra-city zone ─────────────────────────────
const PINCODE_ZONE = {
  // Delhi
  '110005':'Central','110008':'Central','110018':'West','110019':'South',
  '110025':'South','110026':'South','110029':'South','110034':'North',
  '110035':'North','110040':'North','110042':'North','110045':'West',
  '110048':'South','110058':'West','110059':'West','110062':'West',
  '110065':'East','110075':'West','110078':'West','110085':'North',
  '110088':'North','110089':'North','110092':'East','110096':'West',
  // Gurugram/Noida/Faridabad → North
  '122001':'North','122002':'North','122003':'North','122007':'North',
  '122009':'North','122012':'North','122015':'North','122016':'North',
  '122017':'North','122018':'North',
  '121001':'North','121002':'North','121006':'North','121007':'North',
  '201002':'North','201010':'North','201013':'North','201301':'North',
  '201303':'North','201304':'North','201306':'North','201307':'North',
  '201308':'North','201309':'North','201315':'North',
  // Bangalore
  '560010':'South','560013':'North','560022':'Central','560024':'East',
  '560025':'South','560032':'East','560034':'South','560037':'North',
  '560038':'West','560042':'South','560043':'West','560048':'East',
  '560050':'South','560054':'East','560061':'Central','560062':'North',
  '560068':'East','560069':'West','560072':'West','560076':'East',
  '560085':'South','560086':'West','560091':'East','560092':'South',
  '560094':'South','560097':'East','560099':'Central','560100':'South',
  '560102':'South','560103':'South','560105':'South','560111':'South',
  '560114':'South','562125':'North',
  // Mumbai
  '400001':'South','400016':'South','400028':'South','400050':'West',
  '400053':'West','400056':'West','400058':'West','400062':'North',
  '400063':'North','400064':'West','400065':'West','400066':'West',
  '400067':'West','400068':'Central','400069':'Central','400071':'Central',
  '400072':'Central','400076':'Central','400077':'Central','400078':'Central',
  '400079':'Central','400080':'South','400083':'North','400084':'North',
  '400086':'North','400088':'North','400089':'East','400090':'East',
  '400091':'East','400092':'East','400093':'East','400097':'North',
  '400101':'South','400102':'South','400103':'South','400104':'South',
  '400601':'East','400602':'East','400603':'East','400604':'East',
  '400605':'East','400606':'East','400607':'East','400610':'East',
  '400615':'East','400701':'East','400705':'East','400706':'East',
  '400709':'East','410206':'East','410210':'East','421203':'East',
  // Pune
  '411001':'Central','411002':'Central','411004':'Central','411005':'Central',
  '411006':'Central','411007':'Central','411013':'East','411014':'East',
  '411015':'South','411016':'South','411017':'South','411019':'East',
  '411021':'East','411026':'West','411027':'West','411028':'West',
  '411033':'West','411037':'East','411038':'East','411040':'East',
  '411041':'West','411045':'East','411057':'West','411061':'South',
  '412101':'East','412201':'East',
  // Hyderabad
  '500003':'Central','500004':'Central','500008':'West','500013':'Central',
  '500016':'East','500018':'West','500027':'West','500028':'Central',
  '500029':'West','500032':'East','500033':'East','500034':'East',
  '500035':'West','500038':'East','500039':'East','500040':'East',
  '500049':'Central','500060':'East','500072':'West','500073':'West',
  '500074':'West','500079':'West','500081':'West','500084':'East',
  '500085':'East','500096':'West','500101':'West','500114':'West',
  // Ahmedabad
  '380006':'Central','380007':'Central','380009':'Central','380015':'South',
  '380054':'West','380055':'West','380058':'West','380059':'West','380060':'West',
};

function getPincodeZone(pin) {
  return PINCODE_ZONE[String(pin).trim()] || 'Central';
}

// ── City normalizer ───────────────────────────────────────
function normalizeCity(raw) {
  if (!raw) return '';
  const c = raw.trim().toLowerCase();
  if (CONFIG.DELHI_NCR_CITIES.includes(c)) return 'delhi ncr';
  if (c === 'bengaluru' || c === 'bangalore') return 'bangalore';
  if (['mumbai','navi mumbai','thane','navi mumbai'].includes(c)) return 'mumbai';
  if (c === 'pune') return 'pune';
  if (['hyderabad','rangareddy','dakshina kannada'].includes(c)) return 'hyderabad';
  if (c === 'ahmedabad') return 'ahmedabad';
  return c;
}

function normalizeCityBucket(bucket) {
  if (!bucket) return '';
  const b = bucket.trim().toLowerCase();
  if (b === 'delhi') return 'delhi ncr';
  if (b === 'bangalore' || b === 'bengaluru') return 'bangalore';
  return b;
}

function cityLabel(v) {
  if (!v) return 'All Cities';
  return CONFIG.CITY_DISPLAY[v] || v.split(' ').map(w => w[0].toUpperCase()+w.slice(1)).join(' ');
}

// ── Procedure grouping ────────────────────────────────────
const PROCEDURE_GROUPS = {
  'acl reconstruction surgery':'ACL / PCL Reconstruction',
  'adenoidectomy':'Adenoidectomy',
  'allurion intragastric ballooning':'Intragastric Balloon',
  'amputation':'Amputation',
  'ankle fracture surgery':'Fracture Fixation (ORIF / CRIF / IMN)',
  'anorectal surgery':'Anorectal Surgery (General)',
  'av fistula formation':'AV Fistula Formation',
  'axillary breast tissue removal':'Breast Surgery',
  'balanoposthitis':'Circumcision',
  'balloon sinuplasty':'FESS / Sinus Surgery',
  'bankart repair':'Shoulder Surgery (Bankart / Dislocation)',
  'bariatric surgery':'Bariatric / Weight Loss Surgery',
  'body contouring':'Liposuction / Body Contouring',
  'breast augmentation':'Breast Surgery',
  'breast lift':'Breast Surgery',
  'breast lump surgery':'Breast Surgery',
  'breast reconstruction':'Breast Surgery',
  'buccal fat removal (buccal lipectomy)':'Lipoma / Fat Removal',
  'butt lift':'Liposuction / Body Contouring',
  'carpal tunnel release':'Carpal Tunnel Release',
  'circumcision':'Circumcision',
  'closed lateral internal sphincterotomy (lis)':'Fissure Surgery (LIS)',
  'closed reduction':'Fracture Fixation (ORIF / CRIF / IMN)',
  'corn removal':'Skin Lesion Removal',
  'cyst excision':'Cystectomy / Bladder Surgery',
  'cystectomy':'Cystectomy / Bladder Surgery',
  'cystolithotripsy':'Cystolithotripsy',
  'cystoscopic stent removal':'Cystoscopic Stent Removal',
  'debridement':'Debridement',
  'delivery - normal':'Obstetric (Delivery / Pregnancy)',
  'diagnostic arthroscopy':'Knee Arthroscopy',
  'diagnostic cystoscopy':'Diagnostic Cystoscopy',
  'diagnostic hysteroscopy':'Hysteroscopy / Diagnostic Hysteroscopy',
  'dialysis':'Dialysis',
  'disc prolapse treatment':'Spine Surgery',
  'dj stent placement':'DJ Stent Placement',
  'double chin surgery':'Liposuction / Body Contouring',
  'ear correction surgery (otoplasty)':'Eyelid / Ear Surgery',
  'ear membrane surgery (tympanoplasty)':'Tympanoplasty / Ear Membrane Surgery',
  'elbow replacement surgery':'Elbow / Nerve Surgery',
  'endoscopic ablation for a pilonidal sinus':'Pilonidal Sinus Surgery',
  'endoscopic intragastric ballooning':'Intragastric Balloon',
  'endoscopic sleeve gastroplasty':'Bariatric / Weight Loss Surgery',
  'eswl':'ESWL',
  'eye lid surgery':'Eyelid / Ear Surgery',
  'fasciotomy':'Elbow / Nerve Surgery',
  'fat removal':'Lipoma / Fat Removal',
  'fistulotomy':'Fistula Surgery',
  'fracture treatment':'Fracture Fixation (ORIF / CRIF / IMN)',
  'frenuloplasty':'Frenuloplasty',
  'functional endoscopic sinus surgery (fess)':'FESS / Sinus Surgery',
  'gall stones surgery (open cholecystectomy)':'Cholecystectomy (Gallbladder Removal)',
  'ganglion cyst removal':'Ganglion Cyst Removal',
  'ganglion cyst treatment':'Cyst Removal',
  'gastric bypass surgery':'Bariatric / Weight Loss Surgery',
  'genital wart removal':'Genital Wart Removal',
  'gerd surgery':'GERD Surgery',
  'haemorrhoidal artery ligation and recto-anal repair (hal-rar)':'Piles / Haemorrhoid Surgery',
  'haemorrhoidectomy':'Piles / Haemorrhoid Surgery',
  'hal-rar':'Piles / Haemorrhoid Surgery',
  'hip arthroscopy':'Hip Arthroscopy',
  'hydrocele':'Hydrocele Surgery',
  'hydrocele surgery (hydrocelectomy)':'Hydrocele Surgery',
  'hysterectomy':'Hysterectomy',
  'hysteroscopy':'Hysteroscopy / Diagnostic Hysteroscopy',
  'implant removal':'Implant Removal',
  'incision and drainage':'Abscess Drainage (I&D)',
  'incisional hernia surgery':'Hernia Repair',
  'inguinal hernia surgery':'Hernia Repair',
  'inguinal hernioplasty':'Hernia Repair',
  'intragastric balloon removal':'Intragastric Balloon',
  'intramedullary nailing':'Fracture Fixation (ORIF / CRIF / IMN)',
  'kidney stones treatment':'Kidney Stones Treatment (Conservative)',
  'knee arthroscopy':'Knee Arthroscopy',
  'knee pain treatment':'Knee Pain Treatment (Non-Surgical)',
  'laparoscopic appendectomy':'Appendectomy',
  'laparoscopic cholecystectomy':'Cholecystectomy (Gallbladder Removal)',
  'laparoscopic fibroid removal surgery':'Fibroid Removal (Myomectomy)',
  'laparoscopic heminephrectomy':'Laparoscopic Heminephrectomy',
  'laparoscopic hiatal hernia repair':'Hernia Repair',
  'laparoscopic hysterectomy':'Hysterectomy',
  'laparoscopic inguinal hernia repair':'Hernia Repair',
  'laparoscopic ovarian cystectomy':'Ovarian Cystectomy',
  'laparoscopic umbilical hernia surgery':'Hernia Repair',
  'laparoscopic ventral hernia repair':'Hernia Repair',
  'laparoscopy':'Diagnostic Laparoscopy',
  'laser circumcision':'Circumcision',
  'laser excision of mole':'Skin Lesion Removal',
  'laser fissure surgery':'Fissure Surgery',
  'laser fistula surgery':'Fistula Surgery',
  'laser piles surgery':'Piles / Haemorrhoid Surgery',
  'laser pilonidal sinus surgery':'Pilonidal Sinus Surgery',
  'laser prostatectomy':'Laser Prostatectomy',
  'laser surgery for fissure':'Fissure Surgery',
  'laser surgery for fistula':'Fistula Surgery',
  'laser surgery for hydrocele':'Hydrocele Surgery',
  'laser surgery for piles':'Piles / Haemorrhoid Surgery',
  'laser treatment for pilonidal sinus':'Pilonidal Sinus Surgery',
  'laser treatment for varicose veins':'Varicose Veins - Laser Treatment (EVLT)',
  'lateral internal sphincterotomy (lis)':'Fissure Surgery',
  'lip augmentation':'Facial / Lip Augmentation',
  'lipoma removal':'Lipoma / Fat Removal',
  'liposuction':'Liposuction',
  'male breast reduction (gynaecomastia surgery)':'Gynaecomastia (Male Breast Reduction)',
  'marsupialization':'Vaginal Cyst / Marsupialization',
  'mastoidectomy':'Mastoidectomy',
  'meatotomy':'Circumcision',
  'meniscectomy':'Knee Arthroscopy',
  'mole excision':'Mole Excision',
  'myomectomy':'Fibroid Removal (Myomectomy)',
  'myringotomy':'Tympanoplasty / Ear Membrane Surgery',
  'neck lift':'Liposuction / Body Contouring',
  'nephrectomy':'Nephrectomy',
  'nerve repair':'Elbow / Nerve Surgery',
  'neurofibroma excision':'Skin Lesion Removal',
  'non surgical obesity treatment':'Bariatric / Weight Loss Surgery',
  'nose surgery':'Nose Surgery / Polypectomy',
  'open appendectomy':'Appendectomy',
  'open circumcision':'Circumcision',
  'open cystolithotomy':'Cystectomy / Bladder Surgery',
  'open fibroid removal surgery':'Fibroid Removal (Myomectomy)',
  'open lateral internal sphincterotomy (lis)':'Fissure Surgery',
  'open ovarian cystectomy (laparotomy)':'Ovarian Cystectomy',
  'open reduction internal fixation':'Fracture Fixation (ORIF / CRIF / IMN)',
  'open surgery for fissure':'Fissure Surgery',
  'open surgery for fistula':'Fistula Surgery',
  'open surgery for piles':'Piles / Haemorrhoid Surgery',
  'orif hip':'Fracture Fixation (ORIF / CRIF / IMN)',
  'ossiculoplasty':'Mastoidectomy',
  'osteotomy':'Osteotomy',
  'parotidectomy':'Parotidectomy',
  'pcl reconstruction surgery':'ACL / PCL Reconstruction',
  'pcnl':'PCNL',
  'penile frenuloplasty':'Frenuloplasty',
  'peripheral angioplasty':'Peripheral Angioplasty',
  'pilonidal flap surgery':'Pilonidal Sinus Surgery',
  'pilonidal sinus':'Pilonidal Sinus Surgery',
  'polyp removal surgery (polypectomy)':'Nose Surgery / Polypectomy',
  'pregnancy care':'Obstetric (Delivery / Pregnancy)',
  'reduction mammoplasty (breast reduction surgery)':'Breast Surgery',
  'retrogratde intrarenal surgery (rirs)':'RIRS (Retrograde Intrarenal Surgery)',
  'rhinoplasty':'Rhinoplasty',
  'rirs':'RIRS (Retrograde Intrarenal Surgery)',
  'salpingo-oophorectomy':'Salpingo-oophorectomy',
  'scar revision surgery':'Skin Grafting / Scar Revision',
  'sclerotherapy for varicose veins':'Varicose Veins - Sclerotherapy',
  'sebaceous cyst excision':'Sebaceous Cyst Excision',
  'sebaceous cyst removal':'Cyst Removal',
  'septoplasty':'Septoplasty',
  'shoulder dislocation treatment':'Shoulder Surgery (Bankart / Dislocation)',
  'shoulder fracture surgery':'Fracture Fixation (ORIF / CRIF / IMN)',
  'six-pack (liposuction abdomen)':'Liposuction / Body Contouring',
  'skin grafting':'Skin Grafting / Scar Revision',
  'skin tag removal':'Skin Lesion Removal',
  'sleeve gastrectomy':'Bariatric / Weight Loss Surgery',
  'spine non surgical treatment':'Spine Surgery',
  'spine surgery':'Spine Surgery',
  'stapedectomy':'Stapedectomy',
  'stapler circumcision':'Circumcision',
  'stapler surgery for piles':'Piles / Haemorrhoid Surgery',
  'stricturoplasty':'Stricturoplasty',
  'synovectomy':'Synovectomy',
  'tennis elbow release':'Elbow / Nerve Surgery',
  'thrombectomy':'Thrombectomy',
  'thyroidectomy':'Thyroidectomy',
  'toe nail excision':'Skin Lesion Removal',
  'tonsillectomy':'Tonsillectomy',
  'total hip replacement':'Total Hip Replacement (THR)',
  'total knee replacement':'Total Knee Replacement (TKR)',
  'trauma surgery':'Trauma Surgery',
  'tummy tuck (abdominoplasty)':'Tummy Tuck (Abdominoplasty)',
  'turbinate reduction surgery':'FESS / Sinus Surgery',
  'turbt':'TURBT',
  'turp':'TURP',
  'tympanomastoidectomy':'Tympanoplasty / Ear Membrane Surgery',
  'tympanostomy':'Tympanoplasty / Ear Membrane Surgery',
  'umbilical hernia surgery':'Hernia Repair',
  'ureteral stent placement':'DJ Stent Placement',
  'ureteroscopic removal of stone (urs)':'RIRS (Retrograde Intrarenal Surgery)',
  'urethral stricture repair':'Urethral Stricture Repair / Urethrotomy',
  'urethrotomy':'Urethrotomy',
  'ursl':'URSL (Ureteroscopic Stone Lithotripsy)',
  'vaginal cyst removal surgery (marsupialization)':'Vaginal Cyst / Marsupialization',
  'vaginal tightening (vaginoplasty)':'Vaginoplasty',
  'varicocele embolization':'Varicocele Embolization',
  'varicocelectomy':'Varicocelectomy',
  'varicose veins surgery':'Varicose Veins - Open Surgery',
  'venaseal':'Varicose Veins - VenaSeal',
  'venaseal for varicose veins':'Varicose Veins - VenaSeal',
  'ventral hernia surgery':'Hernia Repair',
  'wart removal':'Skin Lesion Removal',
};

function normalizeProcedure(raw) {
  if (!raw) return { group:'Other', original:raw };
  const key = raw.trim().toLowerCase();
  const group = PROCEDURE_GROUPS[key] || PROCEDURE_GROUPS[key.split(';')[0].trim()] || 'Other';
  return { group, original: raw };
}
